In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils._bunch.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X=iris.data

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
len(X)

150

In [9]:
X.shape

(150, 4)

In [10]:
Y = iris.target

In [11]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
Y.shape

(150,)

In [13]:
#one hot encoding
# class 0 --> [1,0,0,...]
# class 1 --> [0,1,0,...]
# class 2 --> [0,0,1,...]

In [14]:
import tensorflow

In [15]:
from keras.utils import to_categorical

In [16]:
Y=to_categorical(Y)

In [17]:
Y.shape

(150, 3)

In [18]:
Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.33,random_state=42)

In [21]:
X_train

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

In [22]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
scalar_object=MinMaxScaler()

In [24]:
scalar_object.fit(X_train)

MinMaxScaler()

In [25]:
scaled_X_train=scalar_object.transform(X_train)

In [26]:
scaled_X_test=scalar_object.transform(X_test)

In [27]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

In [28]:
from keras.models import Sequential
from keras.layers import Dense

In [29]:
model=Sequential()
model.add(Dense(8,input_dim=4,activation="relu"))
model.add(Dense(8,input_dim=4,activation="relu"))
model.add(Dense(3,activation="softmax"))
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139 (556.00 Byte)
Trainable params: 139 (556.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
model.fit(scaled_X_train,y_train,epochs=500,verbose=1)

Epoch 1/500
4/4 [==============================] - 1s 9ms/step - loss: 1.1719 - accuracy: 0.3500
Epoch 2/500
4/4 [==============================] - 0s 5ms/step - loss: 1.1653 - accuracy: 0.3500
Epoch 3/500
4/4 [==============================] - 0s 4ms/step - loss: 1.1606 - accuracy: 0.3500
Epoch 4/500
4/4 [==============================] - 0s 3ms/step - loss: 1.1569 - accuracy: 0.3500
Epoch 5/500
4/4 [==============================] - 0s 4ms/step - loss: 1.1533 - accuracy: 0.3500
Epoch 6/500
4/4 [==============================] - 0s 4ms/step - loss: 1.1494 - accuracy: 0.3500
Epoch 7/500
4/4 [==============================] - 0s 3ms/step - loss: 1.1457 - accuracy: 0.3500
Epoch 8/500
4/4 [==============================] - 0s 3ms/step - loss: 1.1422 - accuracy: 0.3500
Epoch 9/500
4/4 [==============================] - 0s 3ms/step - loss: 1.1381 - accuracy: 0.3500
Epoch 10/500
4/4 [==============================] - 0s 3ms/step - loss: 1.1345 - accuracy: 0.3500
Epoch 11/500
4/4 [===========

4/4 [==============================] - 0s 3ms/step - loss: 0.5631 - accuracy: 0.9200
Epoch 85/500
4/4 [==============================] - 0s 3ms/step - loss: 0.5567 - accuracy: 0.9300
Epoch 86/500
4/4 [==============================] - 0s 5ms/step - loss: 0.5506 - accuracy: 0.9200
Epoch 87/500
4/4 [==============================] - 0s 3ms/step - loss: 0.5446 - accuracy: 0.9100
Epoch 88/500
4/4 [==============================] - 0s 3ms/step - loss: 0.5389 - accuracy: 0.9100
Epoch 89/500
4/4 [==============================] - 0s 4ms/step - loss: 0.5329 - accuracy: 0.9100
Epoch 90/500
4/4 [==============================] - 0s 3ms/step - loss: 0.5274 - accuracy: 0.9200
Epoch 91/500
4/4 [==============================] - 0s 4ms/step - loss: 0.5221 - accuracy: 0.9200
Epoch 92/500
4/4 [==============================] - 0s 5ms/step - loss: 0.5170 - accuracy: 0.9200
Epoch 93/500
4/4 [==============================] - 0s 4ms/step - loss: 0.5115 - accuracy: 0.9200
Epoch 94/500
4/4 [===============

4/4 [==============================] - 0s 5ms/step - loss: 0.2817 - accuracy: 0.9500
Epoch 168/500
4/4 [==============================] - 0s 3ms/step - loss: 0.2791 - accuracy: 0.9500
Epoch 169/500
4/4 [==============================] - 0s 6ms/step - loss: 0.2770 - accuracy: 0.9500
Epoch 170/500
4/4 [==============================] - 0s 5ms/step - loss: 0.2750 - accuracy: 0.9500
Epoch 171/500
4/4 [==============================] - 0s 4ms/step - loss: 0.2727 - accuracy: 0.9600
Epoch 172/500
4/4 [==============================] - 0s 4ms/step - loss: 0.2707 - accuracy: 0.9600
Epoch 173/500
4/4 [==============================] - 0s 4ms/step - loss: 0.2685 - accuracy: 0.9600
Epoch 174/500
4/4 [==============================] - 0s 5ms/step - loss: 0.2660 - accuracy: 0.9600
Epoch 175/500
4/4 [==============================] - 0s 4ms/step - loss: 0.2638 - accuracy: 0.9700
Epoch 176/500
4/4 [==============================] - 0s 4ms/step - loss: 0.2617 - accuracy: 0.9700
Epoch 177/500
4/4 [=====

4/4 [==============================] - 0s 3ms/step - loss: 0.1645 - accuracy: 0.9400
Epoch 250/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1620 - accuracy: 0.9600
Epoch 251/500
4/4 [==============================] - 0s 5ms/step - loss: 0.1605 - accuracy: 0.9700
Epoch 252/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1617 - accuracy: 0.9700
Epoch 253/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1635 - accuracy: 0.9700
Epoch 254/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1614 - accuracy: 0.9700
Epoch 255/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1582 - accuracy: 0.9700
Epoch 256/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1572 - accuracy: 0.9700
Epoch 257/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1564 - accuracy: 0.9600
Epoch 258/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1559 - accuracy: 0.9400
Epoch 259/500
4/4 [=====

4/4 [==============================] - 0s 3ms/step - loss: 0.1164 - accuracy: 0.9600
Epoch 332/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1160 - accuracy: 0.9600
Epoch 333/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1156 - accuracy: 0.9600
Epoch 334/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1150 - accuracy: 0.9600
Epoch 335/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1146 - accuracy: 0.9700
Epoch 336/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1137 - accuracy: 0.9700
Epoch 337/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1136 - accuracy: 0.9700
Epoch 338/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1127 - accuracy: 0.9700
Epoch 339/500
4/4 [==============================] - 0s 5ms/step - loss: 0.1126 - accuracy: 0.9700
Epoch 340/500
4/4 [==============================] - 0s 4ms/step - loss: 0.1121 - accuracy: 0.9700
Epoch 341/500
4/4 [=====

4/4 [==============================] - 0s 5ms/step - loss: 0.0930 - accuracy: 0.9700
Epoch 414/500
4/4 [==============================] - 0s 3ms/step - loss: 0.0942 - accuracy: 0.9600
Epoch 415/500
4/4 [==============================] - 0s 3ms/step - loss: 0.0930 - accuracy: 0.9700
Epoch 416/500
4/4 [==============================] - 0s 3ms/step - loss: 0.0923 - accuracy: 0.9700
Epoch 417/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0907 - accuracy: 0.9700
Epoch 418/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0908 - accuracy: 0.9700
Epoch 419/500
4/4 [==============================] - 0s 3ms/step - loss: 0.0904 - accuracy: 0.9700
Epoch 420/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0916 - accuracy: 0.9700
Epoch 421/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0926 - accuracy: 0.9700
Epoch 422/500
4/4 [==============================] - 0s 3ms/step - loss: 0.0914 - accuracy: 0.9700
Epoch 423/500
4/4 [=====

4/4 [==============================] - 0s 3ms/step - loss: 0.0792 - accuracy: 0.9800
Epoch 496/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0794 - accuracy: 0.9700
Epoch 497/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0787 - accuracy: 0.9700
Epoch 498/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0788 - accuracy: 0.9700
Epoch 499/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0784 - accuracy: 0.9700
Epoch 500/500
4/4 [==============================] - 0s 3ms/step - loss: 0.0783 - accuracy: 0.9700


In [32]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [33]:
model.predict(scaled_X_test)

2/2 [==============================] - 0s 6ms/step


array([[1.12568133e-03, 9.80839133e-01, 1.80352535e-02],
       [9.99160409e-01, 8.39581538e-04, 1.04516684e-09],
       [2.43464712e-07, 2.39204778e-03, 9.97607708e-01],
       [8.42435111e-04, 9.06140745e-01, 9.30168107e-02],
       [7.56561523e-04, 8.73090863e-01, 1.26152545e-01],
       [9.97548997e-01, 2.45103147e-03, 8.80924933e-09],
       [1.94871135e-03, 9.94053185e-01, 3.99814313e-03],
       [3.04058631e-06, 9.62677412e-03, 9.90370214e-01],
       [3.86792322e-04, 3.10274810e-01, 6.89338326e-01],
       [1.57713518e-03, 9.92118835e-01, 6.30399352e-03],
       [5.80293417e-05, 1.36215448e-01, 8.63726556e-01],
       [9.98890460e-01, 1.10952836e-03, 2.87464252e-09],
       [9.99373138e-01, 6.26839348e-04, 8.24114776e-10],
       [9.98953819e-01, 1.04620086e-03, 2.28606822e-09],
       [9.99676228e-01, 3.23807355e-04, 5.18588228e-10],
       [6.07151655e-04, 9.37642276e-01, 6.17506094e-02],
       [1.56334772e-06, 5.04786009e-03, 9.94950533e-01],
       [1.92043453e-03, 9.92011

In [34]:
model.predict_classes(scaled_X_test)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [35]:
predict_x=model.predict(scaled_X_test) 
classes_x=np.argmax(predict_x,axis=1)

2/2 [==============================] - 0s 0s/step


In [36]:
predictions = np.argmax(model.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 0s/step


In [37]:
predictions

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [38]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [39]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [40]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]], dtype=int64)

In [41]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [42]:
accuracy_score(y_test.argmax(axis=1),predictions)

0.96

In [43]:
model.save("myfirstmodel.h5")

C:\Users\Aniket Johri\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [44]:
from keras.models import load_model

In [45]:
new_model=load_model("myfirstmodel.h5")

In [47]:
np.argmax(new_model.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 5ms/step


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)