In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils._bunch.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X=iris.data

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
len(X)

150

In [9]:
X.shape

(150, 4)

In [10]:
Y = iris.target

In [11]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
Y.shape

(150,)

In [13]:
#one hot encoding
# class 0 --> [1,0,0,...]
# class 1 --> [0,1,0,...]
# class 2 --> [0,0,1,...]

In [14]:
import tensorflow

In [15]:
from keras.utils import to_categorical

In [16]:
Y=to_categorical(Y)

In [17]:
Y.shape

(150, 3)

In [18]:
Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.33,random_state=42)

In [24]:
X_train

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [26]:
scalar_object=MinMaxScaler()

In [27]:
scalar_object.fit(X_train)

MinMaxScaler()

In [28]:
scaled_X_train=scalar_object.transform(X_train)

In [29]:
scaled_X_test=scalar_object.transform(X_test)

In [30]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

In [32]:
from keras.models import Sequential
from keras.layers import Dense

In [34]:
model=Sequential()
model.add(Dense(8,input_dim=4,activation="relu"))
model.add(Dense(8,input_dim=4,activation="relu"))
model.add(Dense(3,activation="softmax"))
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139 (556.00 Byte)
Trainable params: 139 (556.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [37]:
model.fit(scaled_X_train,y_train,epochs=500,verbose=2)

Epoch 1/500
4/4 - 1s - loss: 1.0671 - accuracy: 0.3400 - 1s/epoch - 279ms/step
Epoch 2/500
4/4 - 0s - loss: 1.0595 - accuracy: 0.3400 - 20ms/epoch - 5ms/step
Epoch 3/500
4/4 - 0s - loss: 1.0528 - accuracy: 0.3400 - 15ms/epoch - 4ms/step
Epoch 4/500
4/4 - 0s - loss: 1.0464 - accuracy: 0.3400 - 13ms/epoch - 3ms/step
Epoch 5/500
4/4 - 0s - loss: 1.0403 - accuracy: 0.3400 - 13ms/epoch - 3ms/step
Epoch 6/500
4/4 - 0s - loss: 1.0344 - accuracy: 0.3400 - 13ms/epoch - 3ms/step
Epoch 7/500
4/4 - 0s - loss: 1.0287 - accuracy: 0.3400 - 13ms/epoch - 3ms/step
Epoch 8/500
4/4 - 0s - loss: 1.0228 - accuracy: 0.3400 - 14ms/epoch - 3ms/step
Epoch 9/500
4/4 - 0s - loss: 1.0167 - accuracy: 0.3400 - 14ms/epoch - 4ms/step
Epoch 10/500
4/4 - 0s - loss: 1.0106 - accuracy: 0.3500 - 12ms/epoch - 3ms/step
Epoch 11/500
4/4 - 0s - loss: 1.0042 - accuracy: 0.3600 - 13ms/epoch - 3ms/step
Epoch 12/500
4/4 - 0s - loss: 0.9977 - accuracy: 0.4100 - 17ms/epoch - 4ms/step
Epoch 13/500
4/4 - 0s - loss: 0.9908 - accuracy: 

Epoch 104/500
4/4 - 0s - loss: 0.4315 - accuracy: 0.8000 - 12ms/epoch - 3ms/step
Epoch 105/500
4/4 - 0s - loss: 0.4293 - accuracy: 0.7900 - 12ms/epoch - 3ms/step
Epoch 106/500
4/4 - 0s - loss: 0.4269 - accuracy: 0.7800 - 13ms/epoch - 3ms/step
Epoch 107/500
4/4 - 0s - loss: 0.4242 - accuracy: 0.7900 - 13ms/epoch - 3ms/step
Epoch 108/500
4/4 - 0s - loss: 0.4215 - accuracy: 0.7900 - 14ms/epoch - 3ms/step
Epoch 109/500
4/4 - 0s - loss: 0.4186 - accuracy: 0.8400 - 13ms/epoch - 3ms/step
Epoch 110/500
4/4 - 0s - loss: 0.4158 - accuracy: 0.8400 - 16ms/epoch - 4ms/step
Epoch 111/500
4/4 - 0s - loss: 0.4135 - accuracy: 0.8500 - 13ms/epoch - 3ms/step
Epoch 112/500
4/4 - 0s - loss: 0.4100 - accuracy: 0.8900 - 12ms/epoch - 3ms/step
Epoch 113/500
4/4 - 0s - loss: 0.4081 - accuracy: 0.8900 - 13ms/epoch - 3ms/step
Epoch 114/500
4/4 - 0s - loss: 0.4059 - accuracy: 0.9200 - 13ms/epoch - 3ms/step
Epoch 115/500
4/4 - 0s - loss: 0.4031 - accuracy: 0.9200 - 13ms/epoch - 3ms/step
Epoch 116/500
4/4 - 0s - los

4/4 - 0s - loss: 0.2180 - accuracy: 0.9700 - 14ms/epoch - 3ms/step
Epoch 206/500
4/4 - 0s - loss: 0.2169 - accuracy: 0.9700 - 14ms/epoch - 3ms/step
Epoch 207/500
4/4 - 0s - loss: 0.2159 - accuracy: 0.9700 - 14ms/epoch - 4ms/step
Epoch 208/500
4/4 - 0s - loss: 0.2148 - accuracy: 0.9700 - 14ms/epoch - 3ms/step
Epoch 209/500
4/4 - 0s - loss: 0.2129 - accuracy: 0.9700 - 15ms/epoch - 4ms/step
Epoch 210/500
4/4 - 0s - loss: 0.2116 - accuracy: 0.9700 - 16ms/epoch - 4ms/step
Epoch 211/500
4/4 - 0s - loss: 0.2104 - accuracy: 0.9700 - 15ms/epoch - 4ms/step
Epoch 212/500
4/4 - 0s - loss: 0.2101 - accuracy: 0.9700 - 17ms/epoch - 4ms/step
Epoch 213/500
4/4 - 0s - loss: 0.2088 - accuracy: 0.9700 - 18ms/epoch - 5ms/step
Epoch 214/500
4/4 - 0s - loss: 0.2069 - accuracy: 0.9700 - 17ms/epoch - 4ms/step
Epoch 215/500
4/4 - 0s - loss: 0.2054 - accuracy: 0.9700 - 16ms/epoch - 4ms/step
Epoch 216/500
4/4 - 0s - loss: 0.2041 - accuracy: 0.9700 - 15ms/epoch - 4ms/step
Epoch 217/500
4/4 - 0s - loss: 0.2060 - ac

Epoch 307/500
4/4 - 0s - loss: 0.1334 - accuracy: 0.9700 - 15ms/epoch - 4ms/step
Epoch 308/500
4/4 - 0s - loss: 0.1355 - accuracy: 0.9700 - 16ms/epoch - 4ms/step
Epoch 309/500
4/4 - 0s - loss: 0.1329 - accuracy: 0.9700 - 14ms/epoch - 3ms/step
Epoch 310/500
4/4 - 0s - loss: 0.1321 - accuracy: 0.9700 - 15ms/epoch - 4ms/step
Epoch 311/500
4/4 - 0s - loss: 0.1317 - accuracy: 0.9700 - 13ms/epoch - 3ms/step
Epoch 312/500
4/4 - 0s - loss: 0.1311 - accuracy: 0.9700 - 13ms/epoch - 3ms/step
Epoch 313/500
4/4 - 0s - loss: 0.1305 - accuracy: 0.9700 - 14ms/epoch - 4ms/step
Epoch 314/500
4/4 - 0s - loss: 0.1297 - accuracy: 0.9700 - 15ms/epoch - 4ms/step
Epoch 315/500
4/4 - 0s - loss: 0.1299 - accuracy: 0.9700 - 14ms/epoch - 4ms/step
Epoch 316/500
4/4 - 0s - loss: 0.1292 - accuracy: 0.9700 - 14ms/epoch - 3ms/step
Epoch 317/500
4/4 - 0s - loss: 0.1287 - accuracy: 0.9700 - 14ms/epoch - 4ms/step
Epoch 318/500
4/4 - 0s - loss: 0.1285 - accuracy: 0.9700 - 15ms/epoch - 4ms/step
Epoch 319/500
4/4 - 0s - los

4/4 - 0s - loss: 0.0974 - accuracy: 0.9700 - 14ms/epoch - 4ms/step
Epoch 409/500
4/4 - 0s - loss: 0.0971 - accuracy: 0.9700 - 13ms/epoch - 3ms/step
Epoch 410/500
4/4 - 0s - loss: 0.0968 - accuracy: 0.9700 - 12ms/epoch - 3ms/step
Epoch 411/500
4/4 - 0s - loss: 0.0968 - accuracy: 0.9700 - 13ms/epoch - 3ms/step
Epoch 412/500
4/4 - 0s - loss: 0.0963 - accuracy: 0.9700 - 13ms/epoch - 3ms/step
Epoch 413/500
4/4 - 0s - loss: 0.0962 - accuracy: 0.9700 - 14ms/epoch - 4ms/step
Epoch 414/500
4/4 - 0s - loss: 0.0960 - accuracy: 0.9700 - 13ms/epoch - 3ms/step
Epoch 415/500
4/4 - 0s - loss: 0.0956 - accuracy: 0.9700 - 15ms/epoch - 4ms/step
Epoch 416/500
4/4 - 0s - loss: 0.0956 - accuracy: 0.9700 - 14ms/epoch - 4ms/step
Epoch 417/500
4/4 - 0s - loss: 0.0957 - accuracy: 0.9700 - 13ms/epoch - 3ms/step
Epoch 418/500
4/4 - 0s - loss: 0.0954 - accuracy: 0.9700 - 14ms/epoch - 4ms/step
Epoch 419/500
4/4 - 0s - loss: 0.0951 - accuracy: 0.9600 - 16ms/epoch - 4ms/step
Epoch 420/500
4/4 - 0s - loss: 0.0952 - ac

In [38]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [39]:
model.predict(scaled_X_test)

2/2 [==============================] - 0s 14ms/step


array([[9.09978175e-04, 9.79587555e-01, 1.95023585e-02],
       [9.99437034e-01, 5.55996783e-04, 6.95536028e-06],
       [2.55037747e-07, 4.38335148e-04, 9.99561369e-01],
       [9.72026377e-04, 9.24430907e-01, 7.45970085e-02],
       [6.38847763e-04, 8.40175748e-01, 1.59185439e-01],
       [9.98101056e-01, 1.86980714e-03, 2.92056102e-05],
       [2.93892110e-03, 9.89641488e-01, 7.41952239e-03],
       [7.57015096e-06, 9.81221162e-03, 9.90180254e-01],
       [9.38352197e-04, 3.62103224e-01, 6.36958361e-01],
       [1.81198993e-03, 9.87925649e-01, 1.02623235e-02],
       [1.34002650e-04, 2.06176266e-01, 7.93689668e-01],
       [9.98384953e-01, 1.58338691e-03, 3.16038968e-05],
       [9.99429286e-01, 5.61705150e-04, 8.87824172e-06],
       [9.98560131e-01, 1.41381402e-03, 2.61004698e-05],
       [9.99815762e-01, 1.81366559e-04, 2.87564740e-06],
       [4.92874591e-04, 9.68270123e-01, 3.12370192e-02],
       [4.37314156e-06, 5.06508490e-03, 9.94930565e-01],
       [2.40601460e-03, 9.86194

In [42]:
model.predict_classes(scaled_X_test)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [46]:
predict_x=model.predict(scaled_X_test) 
classes_x=np.argmax(predict_x,axis=1)

2/2 [==============================] - 0s 4ms/step


In [50]:
predictions = np.argmax(model.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 5ms/step


In [53]:
predictions

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [52]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [54]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [55]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]], dtype=int64)

In [56]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [57]:
accuracy_score(y_test.argmax(axis=1),predictions)

0.96

In [59]:
model.save("myfirstmodel.h5")